model:
  model_path: Qwen/Qwen3-VL-2B-Instruct
  attn_implementation: flash_attention_2

data:
  train_path: s3://camfer-spice/gcd-run-39/vl-sft-plan-iso/train
  datasets_type: mapping
  dataloader_type: native
  data_type: conversation
  chat_template: qwen_plan_vl
  template_path: templates/qwen-plan-vl.jinja
  max_seq_len: 32768
  train_size: -1
  mm_configs:
    source: null  # Will handle "messages" format automatically
    image_bucket: grabcad  # S3 bucket for images

train:
  output_dir: qwen3_vl_2b_compare
  data_parallel_mode: fsdp2
  enable_reentrant: false
  use_wandb: true
  wandb_project: "gcd-run-39_vl_sft"
  wandb_name: "qwen3_vl_2b_compare"
  rmpad: false
  rmpad_with_pos_ids: true
  ulysses_parallel_size: 1
  freeze_vit: true
  lr: 5.0e-5
  lr_decay_style: cosine
  num_train_epochs: 1
  micro_batch_size: 1
  global_batch_size: 4
  max_steps: 100
  init_device: meta
  enable_profiling: false
  ckpt_manager: dcp
  save_hf_weights: false
  allow_cuda_launch_blocking: false
  checkpoint_upload_path: s3://camfer-spice/gcd-run-39/vl-sft-plan-iso/checkpoints  # S3 path for auto-upload